import { InstagramPost } from '@/lib/content/types'

export const mockInstagramPosts: InstagramPost[] = [
  {
    id: 'seed-1',
    platform: 'instagram',
    title: 'Beautiful sunset over the mountains',
    caption: 'Golden hour magic ✨ Nothing beats watching the sun dip below the mountains. Who else loves sunset photography? 📸\n\n#sunset #mountains #nature #photography #goldenhour',
    postType: 'image',
    status: 'scheduled',
    scheduledFor: '2024-04-15T10:00:00.000Z',
    publishedAt: null,
    metrics: {
      impressions: 3200,
      engagementRate: 4.6,
      likes: 480,
      comments: 32,
      shares: 18,
      reach: 2800,
    },
    createdAt: '2024-04-10T10:00:00.000Z',
    updatedAt: '2024-04-10T10:00:00.000Z',
  },
  {
    id: 'seed-2',
    platform: 'instagram',
    title: 'New Summer Collection Launch',
    caption: 'Swipe to see our brand new Summer 2024 collection! 🌊☀️ Featuring sustainable fabrics and vibrant colors. Available now on our website and in stores!\n\nUse code: SUMMER24 for 20% off your first purchase! 🎉\n\n#SummerCollection #NewArrivals #FashionForChange #SustainableFashion',
    postType: 'carousel',
    status: 'draft',
    scheduledFor: null,
    publishedAt: null,
    metrics: {
      impressions: 0,
      engagementRate: 0,
      likes: 0,
      comments: 0,
      shares: 0,
      reach: 0,
    },
    createdAt: '2024-04-11T12:00:00.000Z',
    updatedAt: '2024-04-11T12:00:00.000Z',
  },
  {
    id: 'seed-3',
    platform: 'instagram',
    title: 'Monthly business update',
    caption: 'Incredible month just behind us! 🚀\n\n📊 Check out our April highlights:\n• 45% increase in online sales\n• 2,500+ new community members\n• Launched 3 new product lines\n• Partnered with 5 amazing local businesses\n\nThank you all for the continued support! 🙏💚\n\n#BusinessGrowth #CommunityFirst #Grateful #MonthlWinUpdate',
    postType: 'video',
    status: 'published',
    scheduledFor: null,
    publishedAt: '2024-04-08T14:00:00.000Z',
    metrics: {
      impressions: 9800,
      engagementRate: 8.2,
      likes: 1200,
      comments: 84,
      shares: 64,
      reach: 8500,
    },
    createdAt: '2024-04-05T09:00:00.000Z',
    updatedAt: '2024-04-08T14:00:00.000Z',
  },
  {
    id: 'seed-4',
    platform: 'instagram',
    title: 'Behind the Scenes: Team Culture',
    caption: "Ever wondered what a day in our office looks like? 🎬\n\nWatch our team in action! From morning meetings to product development sessions, we create an environment where innovation thrives and creativity is celebrated. 💡\n\nWe're hiring! Check our bio for open positions. Join our amazing crew! 🌟\n\n#BehindTheScenes #TeamCulture #NowHiring #ComeJoinUs #WorkCulture",
    postType: 'reel',
    status: 'backlog',
    scheduledFor: null,
    publishedAt: null,
    metrics: {
      impressions: 0,
      engagementRate: 0,
      likes: 0,
      comments: 0,
      shares: 0,
      reach: 0,
    },
    createdAt: '2024-04-09T16:00:00.000Z',
    updatedAt: '2024-04-09T16:00:00.000Z',
  },
  {
    id: 'seed-5',
    platform: 'instagram',
    title: 'Customer Love: Success Stories',
    caption: '💝 Our customers make us what we are!\n\nMeet Jane from Seattle who transformed her wardrobe with our sustainable collection. Her testimonial reminds us why we do this. Best feedback ever! 🙌\n\n"Such quality and style! I feel good knowing my purchase supports ethical fashion."\n\nDo you have a success story? Tag us! We love seeing our products in your lives! 📸\n\n#CustomerLove #Testimonial #SustainableFashion #CommunityShoutOut',
    postType: 'image',
    status: 'published',
    scheduledFor: null,
    publishedAt: '2024-04-06T11:30:00.000Z',
    metrics: {
      impressions: 5600,
      engagementRate: 6.8,
      likes: 720,
      comments: 56,
      shares: 42,
      reach: 4800,
    },
    createdAt: '2024-04-03T08:00:00.000Z',
    updatedAt: '2024-04-06T11:30:00.000Z',
  },
  {
    id: 'seed-6',
    platform: 'instagram',
    title: 'Sustainability Initiative Update',
    caption: "We're going even greener! 🌱\n\n✅ Switched to 100% recyclable packaging\n✅ Carbon-neutral shipping on all orders\n✅ Partnering with 5 environmental nonprofits\n✅ Planting 1 tree for every item sold\n\nOur planet, our future. Let's do this together! 🌍💚\n\n#Sustainability #EcoFriendly #EthicalBusiness #ClimateAction #GreenBusiness",
    postType: 'carousel',
    status: 'published',
    scheduledFor: null,
    publishedAt: '2024-04-02T09:00:00.000Z',
    metrics: {
      impressions: 12400,
      engagementRate: 7.9,
      likes: 1550,
      comments: 127,
      shares: 98,
      reach: 10800,
    },
    createdAt: '2024-03-28T14:00:00.000Z',
    updatedAt: '2024-04-02T09:00:00.000Z',
  },
  {
    id: 'seed-7',
    platform: 'instagram',
    title: 'Live Stream Announcement',
    caption: "Mark your calendars! 📅\n\n🔴 LIVE tomorrow at 2 PM EST\n\nJoining us for an exclusive Q&A session! We'll be answering YOUR questions about:\n• Our design process\n• Upcoming collections\n• Sustainability practices\n• And more!\n\nTune in on Instagram Live or YouTube! Link in bio 🎥\n\n#LiveStream #QAndA #AskUs #ExclusiveContent",
    postType: 'story',
    status: 'draft',
    scheduledFor: null,
    publishedAt: null,
    metrics: {
      impressions: 0,
      engagementRate: 0,
      likes: 0,
      comments: 0,
      shares: 0,
      reach: 0,
    },
    createdAt: '2024-04-12T10:00:00.000Z',
    updatedAt: '2024-04-12T10:00:00.000Z',
  },
  {
    id: 'seed-8',
    platform: 'instagram',
    title: 'Flash Sale Countdown',
    caption: "⏰ 24 HOURS ONLY! ⏰\n\nFlash Sale starts TONIGHT at 8 PM!\n\n🎉 40% OFF everything\n🚚 FREE shipping on orders over $50\n💳 Use code: FLASH24\n\nThis is our biggest sale of the season! Don't miss out. Stock is limited! 🔥\n\nSet a reminder now! Link in bio 🛍️\n\n#FlashSale #BigSale #LimitedTime #ShopNow #DealsAlert",
    postType: 'image',
    status: 'scheduled',
    scheduledFor: '2024-04-14T20:00:00.000Z',
    publishedAt: null,
    metrics: {
      impressions: 2100,
      engagementRate: 5.2,
      likes: 280,
      comments: 24,
      shares: 16,
      reach: 1900,
    },
    createdAt: '2024-04-13T09:30:00.000Z',
    updatedAt: '2024-04-13T09:30:00.000Z',
  },
  {
    id: 'seed-9',
    platform: 'instagram',
    title: 'Influencer Collaboration Reveal',
    caption: "The collab you've been waiting for! 🤝✨\n\nSo excited to announce our partnership with @styleinfluencer and @sustainablefashionblogger!\n\nThey've curated their favorite pieces from our collection and shared styling tips just for you. Tap to see their picks and get inspired! 👆\n\nSpecial discount code for their followers in their linked stories! 💝\n\n#Collaboration #InfluencerPartnership #NewArrivals #StyleInspo",
    postType: 'carousel',
    status: 'published',
    scheduledFor: null,
    publishedAt: '2024-03-31T15:00:00.000Z',
    metrics: {
      impressions: 18900,
      engagementRate: 9.4,
      likes: 2340,
      comments: 186,
      shares: 145,
      reach: 16500,
    },
    createdAt: '2024-03-25T11:00:00.000Z',
    updatedAt: '2024-03-31T15:00:00.000Z',
  },
  {
    id: 'seed-10',
    platform: 'instagram',
    title: 'User Generated Content Feature',
    caption: 'Your style, our inspiration! 📸💕\n\nFeaturing this stunning look by @customerstyle! She paired our Classic Tee with vintage jeans for the perfect casual vibe. Perfection! ✨\n\nWant to be featured? Tag us in your photos with #OurCommunity and you might see yourself on our main feed!\n\nThank you for sharing your creativity! We love seeing how you style our pieces. 🌟\n\n#UserGeneratedContent #CustomerFashion #CommunityLove #StyleInspo #FeaturedCustomer',
    postType: 'image',
    status: 'published',
    scheduledFor: null,
    publishedAt: '2024-04-01T13:00:00.000Z',
    metrics: {
      impressions: 7200,
      engagementRate: 7.1,
      likes: 920,
      comments: 68,
      shares: 52,
      reach: 6100,
    },
    createdAt: '2024-03-29T10:30:00.000Z',
    updatedAt: '2024-04-01T13:00:00.000Z',
  },
]